# Using the remote Midnight theme from GitHub Pages
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # Required for using remote themes

# Other configurations
title: "Karan Yelve's Game Development Portfolio"
description: "Showcasing my journey as a gameplay programmer"
url: "https://your-username.github.io"  # Update with your GitHub Pages URL
baseurl: ""  # Leave empty unless you're using a subdirectory
repository: "karanyelve/portfolio"  # Your GitHub repository name

# Optional: Change theme settings here if you want to customize it
theme: jekyll-theme-midnight  # You can use the local version of Midnight if you prefer

# Social media and other links
social_links:
  github: "https://github.com/karanyelve"
  twitter: "https://twitter.com/karanyelve"
  linkedin: "https://linkedin.com/in/karanyelve"
  # Add more links as needed

# Add any additional customization or configuration here
